feat: Grants sheet modification
Decentraland-DAO/transparency pull request #36
Opened 2023-02-07 13:01 UTC by ncomerci

2023-02-07 18:33 UTC, 1emu requested changes

2023-02-07 18:33 UTC, 1emu commented on src/utils.ts
> +export function getMonthsBetweenDates(startDate: Date, endDate: Date) {
Let's add some tests for this fn please :) there might me some interesting edge cases

2023-02-07 18:33 UTC, 1emu commented on src/interfaces/Grant.ts
> +  duration: number
I'm thinking this name should explicit the units of the duration somehow. 

How about `months_duration` or `duration_in_months`?

2023-02-27 12:15 UTC, andyesp approved these changes

2023-03-01 14:10 UTC, 1emu approved these changes
👏  love the tests <3

2023-03-01 15:12 UTC, merged